=== andrmorenocab/xml/ejercicios_xsl_dtd/ejercicio2.dtd
<!ELEMENT visitas (visita+)>
<!ELEMENT visita (fecha,guia,visitantes)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT guia (#PCDATA)>
<!ELEMENT visitantes (visitante, visitante?, visitante?)>
<!ELEMENT visitante (#PCDATA)>
<!ATTLIST visitante
    idioma (espaÃ±ol | ingles | frances) #REQUIRED
>
<!ATTLIST visitante edad NMTOKEN #REQUIRED>

=== andrmorenocab/xml/ejercicios_xsl_dtd/ejercicio2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE visitas SYSTEM "ejercicio2.dtd">
<visitas>
    <visita>
        <fecha>26-05-2025</fecha>
        <guia>pepe</guia>
        <visitantes>
            <visitante edad="13" idioma="espaÃ±ol">Manuel</visitante>
            <visitante edad="15" idioma="ingles">Carlos</visitante>
            <visitante edad="25" idioma="ingles">Pepe</visitante>
        </visitantes>
    </visita>
    <visita>
        <fecha>26-05-2025</fecha>
        <guia>juan</guia>
        <visitantes>
            <visitante edad="27" idioma="frances">Juan</visitante>
            <visitante edad="24" idioma="frances">Luis</visitante>
        </visitantes>
    </visita>
    <visita>
        <fecha>26-05-2025</fecha>
        <guia>carlos</guia>
        <visitantes>
            <visitante edad="31" idioma="ingles">Alejandro</visitante>
        </visitantes>
    </visita>
</visitas>
