=== andrmorenocab/xml/ejercicios_xsl_dtd/ejercicio3.dtd
<!ELEMENT participaciones (participacion+)>
<!ELEMENT participacion (titulo,foto,comentarios?)>
<!ATTLIST participacion
    categoria (paisaje | retrato | abstracto) #REQUIRED
>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT foto (titulo_foto,archivo)>
<!ELEMENT titulo_foto (#PCDATA)>
<!ELEMENT archivo (#PCDATA)>
<!ELEMENT comentarios (#PCDATA)>

=== andrmorenocab/xml/ejercicios_xsl_dtd/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE participaciones SYSTEM "ejercicio3.dtd">
<participaciones>
    <participacion categoria="paisaje">
        <titulo>participacion 1</titulo>
        <foto>
            <titulo_foto>titulo foto 1</titulo_foto>
            <archivo>foto.jpg</archivo>
        </foto>
        <comentarios>Comentarios</comentarios>
    </participacion>
    <participacion categoria="retrato">
        <titulo>participacion 2</titulo>
        <foto>
            <titulo_foto>titulo foto 2</titulo_foto>
            <archivo>imagen.jpg</archivo>
        </foto>
        <comentarios>Comentarios</comentarios>
    </participacion>
    <participacion categoria="abstracto">
        <titulo>participacion 3</titulo>
        <foto>
            <titulo_foto>titulo foto 3</titulo_foto>
            <archivo>foto.png</archivo>
        </foto>
    </participacion>
</participaciones>
